Reader Topics: Fix MC page
Summary:
This MC page https://[private link]?tags=hello&sort=popularity&_locale=en&refresh=0
was failing with this error:

```
Fatal error: Uncaught Error: Call to undefined function has_meta() in /home/wpcom/public_html/public.api/rest/sal/class.json-api-post-base.php:123 Stack trace: #0 /home/wpcom/public_html/public.api/rest/json-endpoints/class.wpcom-json-api-post-v1-1-endpoint.php(264): SAL_Post->get_metadata() #1 /home/wpcom/public_html/public.api/rest/json-endpoints/class.wpcom-json-api-post-v1-1-endpoint.php(130): WPCOM_JSON_API_Post_v1_1_Endpoint->render_response_keys(Object(WPCOM_Post), 'display', Array) #2 /home/wpcom/public_html/public.api/rest/json-endpoints/class.wpcom-json-api-get-post-v1-1-endpoint.php(70): WPCOM_JSON_API_Post_v1_1_Endpoint->get_post_by('ID', 7265, 'display') #3 /home/wpcom/public_html/public.api/rest/wpcom-json-endpoints/class.wpcom-json-api-read-site-post-endpoint.php(35): WPCOM_JSON_API_Get_Post_v1_1_Endpoint->callback('/read/sites/%s/...', 131300129, 7265) #4 /home/wpcom/public_html/wp-content/lib/reader-site-post/class.wpcom-reader-site-post.php(23): WPCOM_JSON_API_Read_Site_Post_Endpoint->callback('/read/sites/%s/...', 131300129, 7265) #5 /home/wpcom/public_html/wp-content/rest-api-plugins/endpoints/read-tags-cards.php(214): WPCOM_Reader_Site_Post::get_site_post(131300129, 7265) #6 /home/wpcom/public_html/wp-content/rest-api-plugins/endpoints/read-tags-cards.php(180): WPCOM_REST_API_V2_Endpoint_Read_Tags_Cards->process_es_results(Array) #7 /home/missioncontrol/public_html/reader/mobile-endpoints/cards/index.php(95): WPCOM_REST_API_V2_Endpoint_Read_Tags_Cards->get_cards(Array) #8 {main} thrown in /home/wpcom/public_html/public.api/rest/sal/class.json-api-post-base.php on line 123
```

Searching around, it seems that the `has_meta` function is defined not in `wp-includes/post.php` but rather in `wp-admin/includes/post.php`

I am a bit skeptical of this change though, because it seems like it could be potentially breaking many things.

Test Plan:
Apply patch on sandbox and see that cards are properly working for:
https://[private link]?tags=hello&sort=popularity&_locale=en&refresh=0

I feel like it needs a bunch more testing, but not sure exactly what. Will definitely need to make sure that it doesn't break other things.

Reviewers: bluefuton, gibrown

Reviewed By: gibrown

Subscribers: vickikb, sodrowski, jsnmoon, gibrown

Tags: #touches_jetpack_files

Differential Revision: D53904-code

This commit syncs r218377-wpcom.