[not verified] Updated PACKAGE_VERSION number
A required build linter is blocking merging with the following error. I just fixed the version number to make the linter happy.
Linting / Changelogger validity (pull_request) Failing after 1m — Changelogger validity 
Error: Version mismatch, expected 0.2.2-alpha but found 0.2.1!
You might use `tools/project-version.sh -u 0.2.2-alpha packages/post-list` to fix this.