fix: Add unique name to VideoPress e2e tests package (#25411)
* fix: Add unique name to VideoPress e2e tests package

The VideoPress e2e tests package shared a name with the starter-plugin
e2e tests package. This collision caused Metro build errors for the
mobile Gutenberg editor project. Providing a unique name for each
package addresses the collision.

```
jest-haste-map: Haste module naming collision: jetpack-starter-e2e-tests
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>/jetpack/projects/plugins/starter-plugin/tests/e2e/package.json
    * <rootDir>/jetpack/projects/plugins/videopress/tests/e2e/package.json

Failed to construct transformer:  DuplicateError: Duplicated files or mocks. Please check the console for more info
    at setModule (/workdir/gutenberg/node_modules/jest-haste-map/build/index.js:543:17)
    at workerReply (/workdir/gutenberg/node_modules/jest-haste-map/build/index.js:614:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 154227)
    at async /workdir/gutenberg/node_modules/jest-haste-map/build/index.js:426:22
    at async Function.load (/workdir/gutenberg/node_modules/metro/src/node-haste/DependencyGraph.js:143:36) {
  mockPath1: 'jetpack/projects/plugins/starter-plugin/tests/e2e/package.json',
  mockPath2: 'jetpack/projects/plugins/videopress/tests/e2e/package.json'
}
error Duplicated files or mocks. Please check the console for more info.
Error: Duplicated files or mocks. Please check the console for more info
```

* changelog

* fix: Align with package naming convention

Other e2e tests packages utilize a `jetpack-` suffix for the package name.

Co-authored-by: Gerardo Pacheco <gerardo.pacheco@automattic.com>

Co-authored-by: Gerardo Pacheco <gerardo.pacheco@automattic.com>
Co-authored-by: Samiff <samiff@users.noreply.github.com>